version: '3.8'

services:
  mariadb-db:
    image: mariadb:latest
    container_name: mariadb-propiedad
    restart: always
    environment:
      - MARIADB_DATABASE=test_propiedad
      - MARIADB_USER=root
      - MARIADB_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=1234
    ports:
      - "3309:3306"
    volumes:
      - mariadb_propiedad_data:/var/lib/mysql
    networks:
      - lafachada-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  propiedad-service:
    build: .
    container_name: microservicio-propiedad
    restart: always
    depends_on:
      mariadb-db:
        condition: service_healthy
    environment:
      # 💡 Corregido: Ahora apunta a "mariadb-propiedad" (el host real dentro de tu red Docker)
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-propiedad:3306/test_propiedad
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SECURITY_JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8081"
    networks:
      - lafachada-network

volumes:
  mariadb_propiedad_data:

networks:
  lafachada-network:
    external: true


