services:
  mariadb-db:
    image: mariadb:latest
    container_name: mariadb-propiedad
    restart: always
    environment:
      MARIADB_DATABASE: test_propiedad 
      MARIADB_USER: propiedad_test_user
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234 
    ports:
      - "3309:3306"
    volumes:
      - mariadb_propiedad_data:/var/lib/mysql
    networks:
     - lafachada-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  propiedad-service:
    build: .
    container_name: microservicio-propiedad
    restart: always
    depends_on:
      mariadb-db:
        condition: service_healthy
    environment:
     - DB_HOST=mariadb-db
     - DB_PORT=3306
     - DB_NAME=test_propiedad
     - DB_USER=propiedad_test_user
     - DB_PASSWORD=1234
    ports:
     - "8081:8081"
    networks:
     - lafachada-network
volumes:
  mariadb_propiedad_data:

networks:
  lafachada-network:
    external: true
