spring.application.name=propiedad-service
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev
spring.jpa.open-in-view=true
spring.output.ansi.enabled=always